### PR TITLE
Indv project pages

### PR DESCRIPTION
**Pull request by jaynopponep**
- added pop up page desired
- updated correct (new) endpoint for retrieving data
- removed unused project files/code
- edited design of the carousel and the pages themselves
- able to view each project on github with a button

### CODE REVIEW

**Comment by LordFarquaadtheCreator** [comment]
looking good, minor knitpick: 
- remove the ":" colons
- center the text 
Screenshot 2024-06-26 at 9 24 30 PM

**Review by LordFarquaadtheCreator — APPROVED** [review]

**Comment by LordFarquaadtheCreator** [comment]
interestingly, the centering issue doesnt appear in the (QA environment)[https://exp.d1ud9ybook8aha.amplifyapp.com/].
I could've sworn I mentioned it before, but can we make the carasoul scrollable?

**Comment by jaynopponep** [comment]
> looking good, minor knitpick:
> 
> * remove the ":" colons
> * center the text
> 
> Screenshot 2024-06-26 at 9 24 30 PM

Ill take a look
For the scrollable, might be tricky with the original component since I can't seem to find a specific horizontal scroll bar, but it does have arrow keys for changing the slides:
https://www.embla-carousel.com/examples/predefined/

**Comment by LordFarquaadtheCreator** [comment]
> For the scrollable, might be tricky with the original component since I can't seem to find a specific horizontal scroll bar, but it does have arrow keys for changing the slides:

try the `overflow: scroll` css property
if that doesnt work then try the arrows

**Comment by jaynopponep** [comment]
- Removed colons
- Added arrow keys for navigation (removed thumb keys/small buttons)
@LordFarquaadtheCreator 
It's not clear whether the centering is still an issue since I've tried on other browsers, and it also looks fine on this branch and on the experimental link you sent like you said

**Pull request merged**
